<div>
    <a href="/rooms">🔙 Retour</a>
</div>

<h1>Ajouter un bien</h1>
<form action="/rooms" method="post" novalidate>
    <div>
        <label for="input-capacity">Capacity :</label>
        <input type="text" name="capacity" id="input-capacity">
    </div>
    <div>
        <label for="input-surface">Surface :</label>
        <input type="text" name="surface" id="input-surface">
    </div>
    <div>
        <label for="input-price_day">Prix par jour :</label>
        <input type="text" name="price_day" id="input-price_day">
    </div>
    <div>
        <label for="input-description">Nom :</label>
        <input type="text" name="description" id="input-description">
    </div>
    <div>
        <input type="submit" value="Ajouter">
    </div>
</form>