<div>
    <a href="/">RETOUR</a>
</div>
<div>
    <a href="/rooms/add">Ajouter un bien</a>
</div>
<div>
    <a href="/register">create un compte</a>
</div>
<h1>Nos Biens</h1>
<?php if( !empty($rooms) ):?>
<ul>
    <?php foreach( $rooms as $room ):?>
        <li>
            <h1><?php  printf('%s', $room->getDescription() ) ?></h1>
            <ul>
                <li>Id: <?php echo $room->getId() ?></li>
                <li>Capacity: <?php echo $room->getCapacity() ?></li>
                <li>Surface: <?php echo $room->getSurface() ?></li>
                <li>Prix par jour: <?php echo $room->getPrice_day() ?></li>
                <li>Description: <?php echo $room->getDescription() ?></li>
            </ul>
        </li>
    <?php endforeach ?>
</ul>
<?php else: ?>
    <div>Aucun bien disciponible.</div>
<?php endif ?>