<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AhOuais.com</title>
    <link rel="stylesheet" href="/style.css">
</head>
<body>

<h1>Bienvenue sur mon site</h1>

<a href="/rooms-honor">Vous étes un honor</a>

<a href="/rooms-user"> Vous étes un user</a>

<a href="/rooms">Vous étes visiteur</a>

<a href="/login">LOGIN</a>

</body>
</html>