<h1>Locations</h1>


<h1>Détails du rental</h1>

<?php if (!empty($rentals)): ?>
        <?php foreach ($rentals as $rental): ?>
                <div class="room-card">
                    <h2><?php echo $rental->getDescription(); ?></h2>
                    <ul class="room-info">
                        <li><strong>ID:</strong> <?php echo $rental->getId(); ?></li>
                        <li><strong>Capacité:</strong> <?php echo $rental->getCapacity(); ?> personnes</li>
                        <li><strong>Surface:</strong> <?php echo $rental->getSurface(); ?>m²</li>
                        <li><strong>Prix par jour:</strong> <?php echo $rental->getPrice_day(); ?>€</li>
                    </ul>

                    <?php if ($rental->getImage()): ?>
                        <div class="room-image">
                            <img src="<?php echo '/' . $rental->getImage(); ?>" alt="Room Image">
                        </div>
                    <?php else: ?>
                        <p class="no-image">Pas d'image disponible</p>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p>Vous n'avez pas encore réserver de logement.</p>
<?php endif; ?>