<div>
    <a href="/admin">🏠 Retour</a>
</div>

<h1>Liste des chambres</h1>
<?php if( !empty($rooms) ):?>
<ul>
    <?php foreach( $rooms as $room ):?>
        <li>
            <h1><?php  printf('%s %s', $room->getCapacity(), $room->getSurface() ) ?></h1>
            <ul>
                <li>Id: <?php echo $room->getId() ?></li>
                <li>Capacity: <?php echo $room->getCapacity() ?></li>
                <li>Surface: <?php echo $room->getSurface() ?></li>
                <li>Prix par jour: <?php echo $room->getPrice_day() ?></li>
                <li>Description: <?php echo $room->getDescription() ?></li>
            </ul>
        </li>

    <?php endforeach ?>
</ul>
<?php else: ?>
    <div>Il n'y a pas des chambres.</div>
<?php endif ?>